name: Sample 3 - Changes files
on: workflow_dispatch
jobs:
  calculate-changes:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Get the last successful commit
      run: |
        LAST_SUCCESSFUL_COMMIT=$(gh run list --branch main --workflow sample-3.yml --json headSha,conclusion --jq '.[] | select(.conclusion == "success") | .headSha' | head -n 1 || echo "")
        if [ -z "$LAST_SUCCESSFUL_COMMIT" ]; then
          echo "No previous successful commit found. Skipping."
          echo "LAST_SUCCESSFUL_COMMIT=" >> $GITHUB_ENV
        else
          echo "LAST_SUCCESSFUL_COMMIT=$LAST_SUCCESSFUL_COMMIT" >> $GITHUB_ENV
        fi

    - name: Where am I
      run: pwd

    - name: Get the list of changed files
      id: changes
      run: |
        git fetch origin
   #     git diff --name-only $LAST_SUCCESSFUL_COMMIT HEAD > changed_files.txt
    #    echo "CHANGED_FILES=$(cat changed_files.txt)" >> $GITHUB_ENV

    - name: Add changed files to job summary
      run: |
        echo "## Changed files:" >> $GITHUB_STEP_SUMMARY
        while IFS= read -r file; do
          echo "- $file" >> $GITHUB_STEP_SUMMARY
        done < changed_files.txt
